# Generated by Django 4.1.7 on 2023-03-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('img_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
