# Generated by Django 4.1.7 on 2023-03-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0002_cart_class_menu_school_pupil_profile_menuitem_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('comment', models.CharField(max_length=512)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.profile')),
                ('pupil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_meat', models.BooleanField()),
                ('is_fish', models.BooleanField()),
                ('is_gluten', models.BooleanField()),
                ('is_lactose', models.BooleanField()),
                ('is_bob', models.BooleanField()),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.unit')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.meal')),
                ('menu_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.menuitem')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.order')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.dish')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.product')),
            ],
        ),
    ]
