# Generated by Django 4.1.7 on 2023-03-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0003_order_unit_product_orderitem_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='product_dish_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='artishok_website.dish'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='main_dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='artishok_website.dish'),
        ),
    ]
