# Generated by Django 4.1.7 on 2023-03-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0004_ingredient_product_dish_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_glucose',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
