# Generated by Django 4.1.7 on 2023-04-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0006_alter_pupil_id'),
        ('artishok_website', '0007_alter_profile_id'),
    ]

    operations = [
    ]
