# Generated by Django 4.1.7 on 2023-04-29 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0008_merge_0006_alter_pupil_id_0007_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='request_text',
            field=models.CharField(default='null', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='pupil_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.pupil'),
        ),
    ]
