# Generated by Django 4.1.7 on 2023-04-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0009_child_request_text_alter_child_pupil_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='verified',
            field=models.IntegerField(choices=[('wait', 0), ('ok', 1), ('deleted', 2)], default=0),
        ),
    ]
