# Generated by Django 4.1.7 on 2023-04-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0010_alter_child_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='verified',
            field=models.IntegerField(choices=[(0, 'Очікує'), (1, 'Підтверджено'), (2, 'Відхилено')], verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.class', verbose_name='Повний доступ до класу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Користувач'), (1, 'Модератор'), (2, 'Керівник школи'), (3, 'Керівник класу'), (4, 'Адмін')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.school', verbose_name='Повний доступ до школи'),
        ),
    ]
