# Generated by Django 4.1.7 on 2023-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0011_alter_child_verified_alter_profile_class_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='verified',
            field=models.IntegerField(choices=[(0, 'Очікує'), (1, 'Підтверджено'), (2, 'Відхилено')], default=0, verbose_name='Очікує'),
        ),
    ]
