# Generated by Django 4.1.7 on 2023-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0012_alter_child_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='request_text',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Користувач'), (1, 'Модератор'), (2, 'Керівник школи'), (3, 'Керівник класу'), (4, 'Адмін')], default=0),
        ),
    ]
