# Generated by Django 4.1.7 on 2023-05-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0013_remove_child_request_text_alter_profile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Пункт кошика', 'verbose_name_plural': 'Пункти кошика'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Дитина', 'verbose_name_plural': 'Діти'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Клас', 'verbose_name_plural': 'Класи'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Інгредієнт', 'verbose_name_plural': 'Інгредієнти'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Прийом їжі', 'verbose_name_plural': 'Прийоми їжі'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункти меню'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Пункт замовлення', 'verbose_name_plural': 'Пункти замовлення'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Учень', 'verbose_name_plural': 'Учні'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'Школа', 'verbose_name_plural': 'Школи'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Одиниця виміру', 'verbose_name_plural': 'Одиниці виміру'},
        ),
        migrations.AddField(
            model_name='child',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AddField(
            model_name='class',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AddField(
            model_name='dish',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AddField(
            model_name='menu',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AddField(
            model_name='product',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AddField(
            model_name='school',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Видалено (в архіві)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='pupil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.pupil', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.cart', verbose_name='Кошик'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='meal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.meal', verbose_name='Прийом їжі'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.menuitem', verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.profile', verbose_name='Батько'),
        ),
        migrations.AlterField(
            model_name='child',
            name='pupil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.pupil', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='child',
            name='verified',
            field=models.IntegerField(choices=[(0, 'Очікує'), (1, 'Підтверджено'), (2, 'Відхилено')], default=0, verbose_name='Підтверджено'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='img_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на зображення'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='main_dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='artishok_website.dish', verbose_name='Основна страва'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product_dish_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='artishok_website.dish', verbose_name='Страва як інгредієнт основної'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.product', verbose_name='Продукт як інгредієнт'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.school', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.dish', verbose_name='Страва'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вага'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=512, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(verbose_name='Дата та час'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.profile', verbose_name='Профіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pupil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.pupil', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.meal', verbose_name='Прийом їжі'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.menuitem', verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bob',
            field=models.BooleanField(verbose_name='Бобові'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_fish',
            field=models.BooleanField(verbose_name='Риба'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_glucose',
            field=models.BooleanField(verbose_name='Глюкоза'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_gluten',
            field=models.BooleanField(verbose_name='Глютен'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_lactose',
            field=models.BooleanField(verbose_name='Лактоза'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_meat',
            field=models.BooleanField(verbose_name="М'ясо"),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artishok_website.unit', verbose_name='Одиниця виміру'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=28, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.class', verbose_name='Клас'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='phone_number',
            field=models.CharField(blank=True, max_length=28, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
    ]
