# Generated by Django 4.1.7 on 2023-05-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0014_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='count_portion',
            field=models.IntegerField(default=0, verbose_name='Порції'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='count_portion',
            field=models.IntegerField(default=0, verbose_name='Порції'),
        ),
    ]
