# Generated by Django 4.1.7 on 2023-06-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0015_remove_pupil_phone_number_cartitem_count_portion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='comment',
            field=models.CharField(max_length=512, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.meal', verbose_name='Прийом їжі'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(max_length=512, null=True, verbose_name='Коментар'),
        ),
    ]
