# Generated by Django 4.1.7 on 2023-06-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0016_cart_comment_alter_cartitem_meal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Очікує'), (1, 'Готується'), (2, 'Виконано'), (3, 'Відхилено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.dish', verbose_name='Страва'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artishok_website.profile', verbose_name='Профіль'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pupil_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artishok_website.pupil', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Очікує'), (1, 'Готується'), (2, 'Виконано'), (3, 'Відхилено')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.meal', verbose_name='Прийом їжі'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artishok_website.menuitem', verbose_name='Пункт меню'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artishok_website.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.unit', verbose_name='Одиниця виміру'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.class', verbose_name='Повний доступ до класу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.school', verbose_name='Повний доступ до школи'),
        ),
    ]
