# Generated by Django 4.1.7 on 2023-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0017_orderitem_status_alter_menuitem_dish_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('US', 'Користувач'), ('CT', 'Класний менеджер'), ('SD', 'Шкільний менеджер'), ('MD', 'Модератор'), ('AD', 'Адмін')], default='US', max_length=2),
        ),
    ]
