# Generated by Django 4.1.7 on 2023-07-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artishok_website', '0018_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='class_id',
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(default='randcode', max_length=8, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artishok_website.school', verbose_name='Школа'),
        ),
        migrations.CreateModel(
            name='ClassManager',
            fields=[
                ('archived', models.BooleanField(default=False, verbose_name='Видалено (в архіві)')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.profile', verbose_name='Профіль')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artishok_website.school', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Менеджер школи',
                'verbose_name_plural': 'Менеджери шкіл',
            },
        ),
    ]
